### ISSUE TITLE
GpsSetter not working on Magisk 27006

### ISSUE THREAD

**Issue by NaufalHSyahputra** [Android1500/GpsSetter#119]
![Screenshot_20240815-184537](https://github.com/user-attachments/assets/55717082-0775-41c7-a50a-95100d5f0d3e)
GpsSetter not working on Magisk 27006. 

Magisk Version: 27006 (with ZygiskNext module, because in-built zygisk in this magisk version didn't work)
Lsposed Version: 1.9.3_mod (https://github.com/mywalkb/LSPosed_mod/releases, because Lsposed 1.9.2 from official didn't work with ZygiskNext)
Log from Lsposed
[log.txt](https://github.com/user-attachments/files/16627012/log.txt)

**Comment by Android1500** [comment]
> 
> 
> ![Screenshot_20240815-184537](https://github.com/user-attachments/assets/55717082-0775-41c7-a50a-95100d5f0d3e)
> 
> GpsSetter not working on Magisk 27006. 
> 
> 
> 
> Magisk Version: 27006 (with ZygiskNext module, because in-built zygisk in this magisk version didn't work)
> 
> Lsposed Version: 1.9.3_mod (https://github.com/mywalkb/LSPosed_mod/releases, because Lsposed 1.9.2 from official didn't work with ZygiskNext)
> 
> Log from Lsposed
> 
> [log.txt](https://github.com/user-attachments/files/16627012/log.txt)
> 
> 

I am thinking to work on it again with some paid features instead of google map i am going to change openmap and will fix all bugs

**Comment by Guneetgstar** [comment]
Can you give me some insight of the root cause why I am getting this error:
```log
[ 2024-08-25T18:29:26.616    10342: 10901: 10901 E/LSPlant         ] Hook Fails: _ZN3art3jit12JitCodeCache19GarbageCollectCacheEPNS_6ThreadE
[ 2024-08-25T18:29:26.616    10342: 10901: 10901 E/LSPlant         ] Failed to init jit code cache
[ 2024-08-25T18:29:26.616    10342: 10901: 10901 E/LSPosed         ] Failed to init lsplant
[ 2024-08-25T18:29:26.624    10342: 10901: 10901 I/LSPosed         ] Loading xposed for com.android1500.gpssetter/10342
[ 2024-08-25T18:29:26.630    10342: 10901: 10901 I/LSPosed-Bridge  ] Loading legacy module com.android1500.gpssetter from /data/app/~~B5XiXQvYETE3kbGxLYlJIg==/com.android1500.gpssetter-OBlnCtaTJu3Xx5VUiUFGSA==/base.apk
[ 2024-08-25T18:29:26.711    10342: 10901: 10901 I/LSPosed-Bridge  ]   Loading class com.android1500.gpssetter.xposed.HookEntry_YukiHookXposedInit
[ 2024-08-25T18:29:26.757    10342: 10901: 10901 I/LSPosed-Bridge  ] [YukiHookAPI][I]--> Welcome to YukiHookAPI 1.1.6(40)! Using LSPosed API 100
[ 2024-08-25T18:29:26.768    10342: 10901: 10901 I/LSPosed-Bridge  ] [YukiHookAPI][I][android-zygote]--> Find Method [public double android.location.Location.getLatitude()] takes 1ms [Default]
[ 2024-08-25T18:29:26.769    10342: 10901: 10901 I/LSPosed-Bridge  ] [YukiHookAPI][I][android-zygote]--> Find Method [public double android.location.Location.getLongitude()] takes 0ms [Default]
[ 2024-08-25T18:29:26.770    10342: 10901: 10901 I/LSPosed-Bridge  ] [YukiHookAPI][I][android-zygote]--> Find Method [public float android.location.Location.getAccuracy()] takes 0ms [Default]
[ 2024-08-25T18:29:26.771    10342: 10901: 10901 I/LSPosed-Bridge  ] [YukiHookAPI][I][android-zygote]--> Find Method [public void android.location.Location.set(android.location.Location)] takes 0ms [Default]
[ 2024-08-25T18:29:26.776    10342: 10901: 10901 I/LSPosed-Bridge  ] [YukiHookAPI][I][android-zygote]--> Find Method [public android.location.Location android.location.LocationManager.getLastKnownLocation(java.lang.String)] takes 3ms [Default]
[ 2024-08-25T18:29:26.856    10342: 10901: 10901 I/LSPosed         ] New modules detected, hook preferences
[ 2024-08-25T18:29:26.857    10342: 10901: 10901 E/LSPosed         ] error when hooking LoadedApk#createClassLoader: pkg=com.android1500.gpssetter, prc=com.android1500.gpssetter
java.lang.NoSuchMethodError: android.app.ContextImpl#checkMode(int)#exact
	at ssFufGWabeqBOOo.Fm.b.L.XposedHelpers.lambda$findMethodExact$3(Unknown Source:6)
	at ssFufGWabeqBOOo.Fm.b.L.XposedHelpers.h(Unknown Source:0)
	at ssFufGWabeqBOOo.Fm.b.L.c.get(Unknown Source:7)
	at java.util.Optional.orElseThrow(Optional.java:403)
	at ssFufGWabeqBOOo.Fm.b.L.XposedHelpers.findMethodExact(SourceFile:5)
	at ssFufGWabeqBOOo.Fm.b.L.XposedHelpers.findAndHookMethod(SourceFile:3)
	at ssFufGWabeqBOOo.Fm.b.L.XposedHelpers.findAndHookMethod(SourceFile:6)
	at h0.b(Unknown Source:96)
	at h0.a(Unknown Source:229)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:253)
	at LSPHooker_.createOrUpdateClassLoaderLocked(Unknown Source:11)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1130)
	at android.app.LoadedApk.getResources(LoadedApk.java:1378)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3326)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3318)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7186)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2337)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
[ 2024-08-25T18:29:44.980     2000: 11168: 11168 E/LSPlant         ] Hook Fails: _ZN3art3jit12JitCodeCache19GarbageCollectCacheEPNS_6ThreadE
[ 2024-08-25T18:29:44.980     2000: 11168: 11168 E/LSPlant         ] Failed to init jit code cache
[ 2024-08-25T18:29:44.980     2000: 11168: 11168 E/LSPosed         ] Failed to init lsplant
[ 2024-08-25T18:29:45.033     2000: 11168: 11168 I/LSPosed         ] Loaded manager, skipping next steps
```

I am happy to contribute and fix it.

I am using:
Magisk 27.0(27000) with zygisk
LSposed mod version 1.9.3_mod (7244)
on Pixel 7 Android 14

**Comment by Eunice4869** [comment]
> ![Screenshot_20240815-184537](https://private-user-images.githubusercontent.com/17007647/358277684-55717082-0775-41c7-a50a-95100d5f0d3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDI1NDgsIm5iZiI6MTcyNDY0MjI0OCwicGF0aCI6Ii8xNzAwNzY0Ny8zNTgyNzc2ODQtNTU3MTcwODItMDc3NS00MWM3LWE1MGEtOTUxMDBkNWYwZDNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDAzMTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2Y2FmMmRjYTY2NWIyMjgyMTM4MWI4MjE0YTY2YzU5YjI2NzVlZWRiNWM2ODMxNGI4ZjA1ZGY3ODA1OTg4MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5qKiIzd8h2qnJIBdFd5nfYxrid4wVhFSZT7gHPaoSLk) GpsSetter not working on Magisk 27006.
> 
> Magisk Version: 27006 (with ZygiskNext module, because in-built zygisk in this magisk version didn't work) Lsposed Version: 1.9.3_mod (https://github.com/mywalkb/LSPosed_mod/releases, because Lsposed 1.9.2 from official didn't work with ZygiskNext) Log from Lsposed [log.txt](https://github.com/user-attachments/files/16627012/log.txt)

Magisk 27007 was released  
Is it fixed in that version??? 
Update please

**Comment by Guneetgstar** [comment]
> Magisk 27007 was released Is it fixed in that version??? Update please

Not tested on the newer Magisk version but I don't think this is anywhere related to Magisk. The [YukiHookAPI](https://highcapable.github.io/YukiHookAPI/en/) used in the project to hook to the system process is getting failed. I thought upgrading the YukiAPI version might fix it but no while the other apps (not using YukiHookAPI) are working just fine. It is happening since I switched to LSPosed_mod and since then I am not able to downgrade to LSPosed as it doesn't work on my device anymore.

**Comment by Android1500** [comment]
> > Magisk 27007 was released Is it fixed in that version??? Update please
> 
> 
> 
> Not tested on the newer Magisk version but I don't think this is anywhere related to Magisk. The [YukiHookAPI](https://highcapable.github.io/YukiHookAPI/en/) used in the project to hook to the system process is getting failed. I thought upgrading the YukiAPI version might fix it but no while the other apps (not using YukiHookAPI) are working just fine. It is happening since I switched to LSPosed_mod and since then I am not able to downgrade to LSPosed as it doesn't work on my device anymore. 

Right now my all focus to release next version of android faker with latest xposed api v100 after successfull release i will start to work on Gps setter lots of users face different issues coz you module need a upgrade it can't match recent changes and by looking your logs its seems like it not compatable with lsposed mod

**Comment by Guneetgstar** [comment]
> by looking your logs its seems like it not compatable with lsposed mod

Well LSPosed is archived and not be getting any updates while LSPosed_mod seems the next alternative so any future releases must be compatible with [LSPosed_mod](https://github.com/mywalkb/LSPosed_mod)

**Comment by yo-less** [comment]
I managed to get it working again using this Lsposed Mod fork: https://github.com/JingMatrix/LSPosed/releases/tag/v1.10.0

**Comment by gustov3n** [comment]
> I managed to get it working again using this Lsposed Mod fork: https://github.com/JingMatrix/LSPosed/releases/tag/v1.10.0

Thank you so much, it worked for me

**Comment by Lnlythinkrzz** [comment]
Please help me,, I also faced this problem..

**Comment by Lnlythinkrzz** [comment]
Thank you so so so so much Brother,, tussi great ho... It's 100% working.. thanks again and again... Love you..

**Comment by Adars896** [comment]
Please help me,, I also faced this problem

**Comment by Adars896** [comment]
Please help me,, I also faced this problem
