### ISSUE TITLE
gpssetter silently crashes when "set location" button is clicked

### ISSUE THREAD

**Issue by modularanne** [Android1500/GpsSetter#66]
Stack trace posted following. 

"DEADLINE_EXCEEDED: deadline exceeded after 4.912916000s" is the most noteworthy part of the log. 

Tried 1.2.8, 1.2.10… 1.30-beta - all with same. Silent error. 

`FATAL EXCEPTION: main
Process: com.android1500.gpssetter, PID: 2767
java.io.IOException: efjr: DEADLINE_EXCEEDED: deadline exceeded after 4.912916000s. [closed=[], open=[[buffered_nanos=4913157308, waiting_for_connection]]]
	at android.location.Geocoder$GeocodeListener.getResults(Geocoder.java:246)
	at android.location.Geocoder.getFromLocation(Geocoder.java:134)
	at com.android1500.gpssetter.utils.ext.Ext_LatLngKt$getAddress$2$1.invokeSuspend(Ext+LatLng.kt:16)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@941653e, Dispatchers.Main.immediate]`

**Comment by Android1500** [comment]
> Stack trace posted following. 
> 
> 
> 
> "DEADLINE_EXCEEDED: deadline exceeded after 4.912916000s" is the most noteworthy part of the log. 
> 
> 
> 
> Tried 1.2.8, 1.2.10… 1.30-beta - all with same. Silent error. 
> 
> 
> 
> `FATAL EXCEPTION: main
> 
> Process: com.android1500.gpssetter, PID: 2767
> 
> java.io.IOException: efjr: DEADLINE_EXCEEDED: deadline exceeded after 4.912916000s. [closed=[], open=[[buffered_nanos=4913157308, waiting_for_connection]]]
> 
> 	at android.location.Geocoder$GeocodeListener.getResults(Geocoder.java:246)
> 
> 	at android.location.Geocoder.getFromLocation(Geocoder.java:134)
> 
> 	at com.android1500.gpssetter.utils.ext.Ext_LatLngKt$getAddress$2$1.invokeSuspend(Ext+LatLng.kt:16)
> 
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 
> 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
> 
> 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
> 
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
> 
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
> 
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
> 
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
> 
> 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@941653e, Dispatchers.Main.immediate]`

Thanks to give log i will take a look into this

**Comment by 7errie** [comment]
Not sure if this helps, but I had the same issue once. But I figured out that it will keep happening unless you clear the app data (SD Maid). 

It feels like the error might cause some memory leak of some sort. Maybe garbage collection is needed if the app fails to set a position?

**Comment by L0caler** [comment]
same problem. Ressetting Data in settings or in the app SD Maid didnt help.
Also except for the very first time when i opened it, the map is grey and the location buttons dont do anything. Doesnt matter if i reset the app or uninstall the module, still grey.
![image](https://github.com/Android1500/GpsSetter/assets/37247327/f0913162-ed41-47c4-9001-4270d4d1c914)

**Comment by LexPanda9** [comment]
> same problem. Ressetting Data in settings or in the app SD Maid didnt help. Also except for the very first time when i opened it, the map is grey and the location buttons dont do anything. Doesnt matter if i reset the app or uninstall the module, still grey. ![image](https://github.com/Android1500/GpsSetter/assets/37247327/f0913162-ed41-47c4-9001-4270d4d1c914)

If anyone is still having issues where gps setter crashes when you select location or search, all you have to do is downgrade your playstore version. It perfectly works on my playstore version 21.8.19 but if my playstoe automatically upgrades to version 47 it starts crashing. So remember to turn off auto update when you downgrade your play store

I hope this helps someone out there
